### ISSUE TITLE
Flow build fails

### ISSUE THREAD

**Issue by wilddeuces** [rromannissen/nifi-openshift#1]
Hello,

after building the Base I want to start a new build with: oc start-build nifi-ocp --from-file=./flow
I am running OpenShift 4.1.11
Steps to reproduce:
Built nifi-base docker repo on quay.io
Created ImageStream in NameSpace including nifi-base docker repo
Created BuildConfig like in Readme
oc start-build nifi-ocp --from-file=./base
Edited the nifi-flow.yaml to match OpenShift 4 Patterns
oc new-app nifi-flow.yaml --param=APPLICATION-NAME=nifi-ocp
Edited Flow Dockerfile to Pull from intern registry
oc start-build nifi-ocp --from-file=./flow

The Build logs show me:

Receiving source from STDIN as archive ...
Caching blobs under "/var/cache/blobs".

Pulling image image-registry.openshift-image-registry.svc:5000/apache/nifi-ocp ...
Getting image source signatures
Copying blob sha256:e6cb98e32a52e3d74381e6d9719bf33482c3b5fcf2825b76102321be48773821
Copying blob sha256:2383fa4462e7d53413577c765054e9e0e3de37aa279d3b672705f0885d590f18
Copying blob sha256:7ac3ce9f206757c3db4ed7aca207db18b600c1e0a0f0ff454629673568b95f72
Copying blob sha256:ae1b8d879badee51dc9d6e27a496eccd69979e406f851fc456990c2b995ff6e8
Copying blob sha256:9cc2ad81d40d54dcae7fa5e8e17d9c34e8bba3b7c2cc7e26fb22734608bda32e
Copying blob sha256:ce9a16d8ddcb3a3d027d25aeba809aee980512db64066462e0c261a1e7dbaf89
Copying blob sha256:d8f550da49900ffd0dbd032896b617a1bb533e2cc328fe174b41f628a5bf635a
Copying config sha256:b3a6f8b51409a099e235aff314443d6400c7872af9503adfc9971e792a493f8b
Writing manifest to image destination
Storing signatures
STEP 1: FROM image-registry.openshift-image-registry.svc:5000/apache/nifi-ocp
STEP 2: ADD flow.xml.gz /opt/nifi/nifi-current/conf/flow.xml.gz
error: build error: error building at STEP "ADD flow.xml.gz /opt/nifi/nifi-current/conf/flow.xml.gz": no files found matching "/tmp/build/inputs/flow.xml.gz": no such file or directory

Thanks in advance for a response.

Cheers

**Comment by wilddeuces** [comment]
I forgot to add a flow file in the folder...

**Comment by keremceliker** [comment]
which folder did you copy to flow.yml by the way ? another point is then did it work ? or did you do any different run on it ?
