### ISSUE TITLE
I forgot to add a flow file in the folder...

### ISSUE THREAD

**Issue by keremceliker** [rromannissen/nifi-openshift#3]
which folder did you copy flow by the way ? another point is then did it work ? or did you do any different run on it ?

I forgot to add a flow file in the folder...

_Originally posted by @wilddeuces in https://github.com/rromannissen/nifi-openshift/issues/1#issuecomment-527135934_

**Comment by wilddeuces** [comment]
The flowfile has to be added into the "Flow" directory. You can check the Dockerfile in each directory to understand what is happening with each file.

Cheers

**Comment by keremceliker** [comment]
Thanks Mate ! Could you try this repo on MiniShift for me if its possible ? 
give me a favor that really would be awesome for me. Because it doesnt work
