### ISSUE TITLE
cannot create .nifi-cli.nifi.properties file

### ISSUE THREAD

**Issue by willimoa** [rromannissen/nifi-openshift#5]
Thanks for making this repository available.
I am attempting to run the created image in docker (before deploying to openshift). - Is it possible to use this to build a docker image and run in docker before deploying to openshift ?

from "docker logs xxx"
/opt/nifi/scripts/toolkit.sh: 18: /opt/nifi/scripts/toolkit.sh: cannot create //.nifi-cli.nifi.properties: Permission denied.

It appears that the {$HOME} in this line from toolkit.sh is not defined, or is defined as "/":
cat <<EOT > ${HOME}/.nifi-cli.config

Where is ${HOME} defined ?   (I assume this is for user 1001 and does not have $HOME set as the user does not exist)jjjjjjjjj

(I have updated the Dockerfile to use nifi Version 12.1, the current version)

**Comment by willimoa** [comment]
Mentioned in earlier issue : https://github.com/rromannissen/nifi-openshift/issues/4#issuecomment-655312580
> The problem has been Fixed... The reason for the problem is the permission issue caused by the Dockerfile that came in the catalog. Generally a bug Apache NiFi-sourced on OpenShift when u want to run on it with Docker Image...
> 
> Kerem Çeliker

How was this fixed ?    I had the same problem.  but the last comment implies issues with running with docker image, which is what I'm trying to do (as an interim step).   P.S.  to get around the linked problem I changed HOME to NIFI_HOME in the common and toolkit sh scripts, but I still haven't got my container running.

**Comment by dolgmax** [comment]
Hello @willimoa 
Have you fixed the " cannot create //.nifi-cli.nifi.properties: Permission denied." error?
How did you do that?

**Comment by willimoa** [comment]
Hello @dolgmax,
Yes, but I relied on my Openshift guy to fix it.  I think it was an issue with the user setup.  I'll check my modified Dockerfile.
